name: go-logger Build/Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Pull repo
      uses: actions/checkout@v3
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=15m
        skip-build-cache: true
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Install dependencies
      run: go get .
    - name: Test with the Go CLI
      run: go test ./...
